---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: flask-app
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001